### ISSUE TITLE
camera组件的宽高不能设置百分比

### ISSUE THREAD

**Issue by carry5250** [react-native-oh-library/react-native-vision-camera#60]
### 描述 / Description

camera组件的宽高不能设置百分比

### 复现步骤 / Steps to reproduce

1，导入camera组价
2，设置组件的style样式。例如，(width: '100%',height:'40%')
3，观察组件的样式是否生效

### 库版本 / Library version

4.0.1-0.0.15

### React Native OpenHarmony version

0.72.29

### 构建类型 / Build type

None

### 设备 / Device

None

### 设备版本 / Device model

mate60pro

### 已悉知 / Acknowledgements

Yes

**Comment by yinliang201710** [comment]
视频录制后stopRecording后声音还在一直在播放
